name: Auto Release Draft

on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Last Draft Release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "release|prerelease"
          view_top: 1

      - name: Publish Draft Release
        if: steps.last_release.outputs.id
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          id: ${{ steps.last_release.outputs.id }}
