name: PR Labeler

on:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: TimonVS/pr-labeler-action@8b99f404a073744885d8021d1de4e40c6eaf38e2 # v4.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
