name: Release Drafter

on:
  push:
    branches: [main, 'release/*']

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@234c54319f675ec6360d7f892fd62399bac71c0a # v5.0.0
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
