name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Parse version from tag
        id: version
        uses: release-kit/semver@v1
        with:
          input: ${{ github.event.release.tag_name }}

      - name: Checkout to released tag
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.version.outputs.tag }}

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Check build cache
        id: cache
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ hashFiles('./yarn.lock', './src/**', './rollup.config.js', './jest.config.js') }}

      - name: Create a new build
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn build

      - name: Set version from release
        uses: reedyuk/npm-version@1.0.1
        with:
          version: ${{ steps.version.outputs.full }}

      - name: Create NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish latest
        if: ${{ steps.version.outputs.prerelease == null }}
        run: npm publish

      - name: Publish RC
        if: ${{ steps.version.outputs.prerelease != null }}
        run: npm publish --tag ${{ steps.version.outputs.prerelease }}

      - name: Force update remote latest release branch
        run: git push origin ${{ steps.version.outputs.tag }}:release/latest -f

      - name: Force update remote major release branch
        run: git push origin ${{ steps.version.outputs.tag }}:release/${{ steps.version.outputs.major }} -f