name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Parse version from tag
        id: version
        uses: release-kit/semver@v1
        with:
          input: ${{ github.event.release.tag_name }}

      - name: Checkout to latest release branch
        uses: actions/checkout@v3
        with:
          ref: release/latest
          fetch-depth: 0

      - name: Sync latest release branch with released tag
        run: git reset --hard ${{ steps.version.outputs.tag }}

      - name: Push latest release branch to remote
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.FULL_ACCESS_GITHUB_TOKEN }}
          branch: release/latest
          tags: true
          force: true
          unprotect_reviews: true

      - name: Checkout to major release branch
        uses: actions/checkout@v3
        with:
          ref: release/${{ steps.version.outputs.major }}
          fetch-depth: 0

      - name: Sync major release branch with released tag
        run: git reset --hard ${{ steps.version.outputs.tag }}

      - name: Push major release branch to remote
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.FULL_ACCESS_GITHUB_TOKEN }}
          branch: release/${{ steps.version.outputs.major }}
          tags: true
          force: true
          unprotect_reviews: true

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Check build cache
        id: cache
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ hashFiles('./yarn.lock', './src/**', './rollup.config.js', './jest.config.js') }}

      - name: Create a new build
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn build

      - name: Set version from release
        uses: reedyuk/npm-version@1.0.1
        with:
          version: ${{ steps.version.outputs.tag }}

      - name: Create NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish latest
        if: ${{ steps.version.outputs.prerelease == null }}
        run: npm publish

      - name: Publish RC
        if: ${{ steps.version.outputs.prerelease != null }}
        run: npm publish --tag ${{ steps.version.outputs.prerelease }}