name: Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Use build cache
        id: cache
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ hashFiles('./yarn.lock', './src/**', './rollup.config.js', './jest.config.js') }}

      - name: Create a new build
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn build

      - name: Save build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

      - name: Merge dev -> main
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.FULL_ACCESS_GITHUB_TOKEN }}
          source_ref: ${{ github.event.release.tag_name }}
          target_branch: 'main'
          commit_message_template: 'ci: merge {source_ref} tag into {target_branch}'

      - uses: actions/checkout@v3

      - name: Restore build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Extract version
        id: tag
        uses: olegtarasov/get-tag@v2.1.1
        with:
          tagRegex: 'v(.*)'

      - name: Set version from release
        uses: reedyuk/npm-version@1.0.1
        with:
          version: ${{ steps.tag.outputs.tag }}

      - name: Create NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: npm publish