name: Release Auto-Update

on:
  pull_request:
    types:
      - closed
    paths:
      - './package.json'
      - './yarn.lock'

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'renovate/typescript-preset' }}
    steps:
      # The auto-update is merged directly into release branch,
      # since we don't need to include the dev changes from main in the auto-release
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release

      - name: Bump and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          WITH_V: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the new tag
        uses: actions/checkout@v3
        with:
          ref: release

      # Just check if the version has a rc-like postfix
      # If so, the Github release should be marked as prerelease
      - name: Extract version
        id: tag
        uses: olegtarasov/get-tag@v2.1.1
        with:
          tagRegex: 'v(?<version>[0-9.]*)(?:-(?<rc>.*))?'

      # We actually don't update the package in this workflow
      # We just create a Github release, just like in regular release-cycle
      # The "release" workflow will handle it next
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          body: 'Auto-update dependencies'
          prerelease: ${{ steps.tag.outputs.rc != null }}
          token: ${{ secrets.GITHUB_TOKEN }}